from ...models import Product
from decimal import Decimal
from django.utils import lorem_ipsum

class SeedProducts:
    # es ia
    PRODUCTS = [
    # Electrónicos (20 productos)
    Product(name="Smartphone Alta Gama 2025", description=lorem_ipsum.paragraph(), price=Decimal('999.99'), stock=50, tags="Electrónica, Smartphone, Móvil, Tecnología", active=False),
    Product(name="Laptop Ultraligera Pro", description=lorem_ipsum.paragraph(), price=Decimal('1250.00'), stock=30, tags="Electrónica, Laptop, Computadora, Profesional"),
    Product(name="Tablet Creativa 10 pulgadas", description=lorem_ipsum.paragraph(), price=Decimal('450.50'), stock=75, tags="Electrónica, Tablet, Creatividad, Portátil"),
    Product(name="Auriculares Inalámbricos ProSound", description=lorem_ipsum.paragraph(), price=Decimal('199.90'), stock=120, tags="Electrónica, Audio, Auriculares, Inalámbrico"),
    Product(name="Smartwatch Deportivo FitMax", description=lorem_ipsum.paragraph(), price=Decimal('230.00'), stock=90, tags="Electrónica, Smartwatch, Deporte, Salud"),
    Product(name="Teclado Mecánico Gamer RGB", description=lorem_ipsum.paragraph(), price=Decimal('150.75'), stock=60, tags="Electrónica, Gaming, Teclado, PC"),
    Product(name="Mouse Ergonómico ProClick", description=lorem_ipsum.paragraph(), price=Decimal('65.00'), stock=150, tags="Electrónica, PC, Mouse, Ergonómico"),
    Product(name="Monitor Curvo 27 pulgadas QHD", description=lorem_ipsum.paragraph(), price=Decimal('399.99'), stock=40, tags="Electrónica, Monitor, Pantalla, PC"),
    Product(name="Cámara Mirrorless ProShot 24MP", description=lorem_ipsum.paragraph(), price=Decimal('850.00'), stock=25, tags="Electrónica, Fotografía, Cámara, Video"),
    Product(name="Altavoz Bluetooth Portátil X-Bass", description=lorem_ipsum.paragraph(), price=Decimal('89.99'), stock=200, tags="Electrónica, Audio, Altavoz, Portátil"),
    Product(name="Cargador Portátil PowerBank 20000mAh", description=lorem_ipsum.paragraph(), price=Decimal('45.50'), stock=180, tags="Electrónica, Móvil, Batería, Cargador"),
    Product(name="TV LED 55 pulgadas 4K UHD Smart", description=lorem_ipsum.paragraph(), price=Decimal('650.00'), stock=35, tags="Electrónica, TV, SmartTV, Entretenimiento"),
    Product(name="Consola de Videojuegos NextGen", description=lorem_ipsum.paragraph(), price=Decimal('599.00'), stock=55, tags="Electrónica, Gaming, Consola, Videojuegos"),
    Product(name="Drone Plegable con Cámara 4K", description=lorem_ipsum.paragraph(), price=Decimal('320.99'), stock=40, tags="Electrónica, Drone, Fotografía Aérea, Gadget"),
    Product(name="Router WiFi 6 Mesh System", description=lorem_ipsum.paragraph(), price=Decimal('180.25'), stock=70, tags="Electrónica, Redes, WiFi, Internet"),
    Product(name="Proyector Portátil HD CineHome", description=lorem_ipsum.paragraph(), price=Decimal('275.00'), stock=30, tags="Electrónica, Proyector, Cine en Casa, Entretenimiento"),
    Product(name="Barra de Sonido Dolby Atmos", description=lorem_ipsum.paragraph(), price=Decimal('350.00'), stock=45, tags="Electrónica, Audio, Sonido Envolvente, TV"),
    Product(name="Lector de eBooks PaperLight", description=lorem_ipsum.paragraph(), price=Decimal('129.99'), stock=100, tags="Electrónica, Lectura, eBook, Portátil"),
    Product(name="Cámara de Seguridad WiFi Exterior", description=lorem_ipsum.paragraph(), price=Decimal('99.50'), stock=80, tags="Electrónica, Seguridad, Hogar Inteligente, Vigilancia"),
    Product(name="Micrófono USB Condensador Studio", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=65, tags="Electrónica, Audio, Grabación, Podcasting"),

    # Ropa (20 productos)
    Product(name="Camiseta Algodón Orgánico Básica", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=300, tags="Ropa, Básico, Algodón, Sostenible"),
    Product(name="Pantalón Vaquero Slim Fit Hombre", description=lorem_ipsum.paragraph(), price=Decimal('59.95'), stock=150, tags="Ropa, Hombre, Pantalón, Vaquero"),
    Product(name="Vestido Floral Verano Mujer", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=120, tags="Ropa, Mujer, Vestido, Verano"),
    Product(name="Chaqueta Impermeable Montaña Unisex", description=lorem_ipsum.paragraph(), price=Decimal('120.75'), stock=80, tags="Ropa, Unisex, Chaqueta, Outdoor"),
    Product(name="Sudadera con Capucha Logo Clásico", description=lorem_ipsum.paragraph(), price=Decimal('65.50'), stock=200, tags="Ropa, Casual, Sudadera, Urbano"),
    Product(name="Pantalones Deportivos Transpirables", description=lorem_ipsum.paragraph(), price=Decimal('39.99'), stock=180, tags="Ropa, Deporte, Pantalón, Fitness"),
    Product(name="Camisa de Lino Manga Larga Hombre", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=100, tags="Ropa, Hombre, Camisa, Lino"),
    Product(name="Blusa Elegante Seda Mujer", description=lorem_ipsum.paragraph(), price=Decimal('75.90'), stock=90, tags="Ropa, Mujer, Blusa, Elegante"),
    Product(name="Conjunto Deportivo Niño/Niña", description=lorem_ipsum.paragraph(), price=Decimal('49.95'), stock=110, tags="Ropa, Infantil, Deporte, Conjunto"),
    Product(name="Pijama de Algodón Bebé (Pack 2)", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=130, tags="Ropa, Bebé, Pijama, Algodón"),
    Product(name="Falda Midi Plisada", description=lorem_ipsum.paragraph(), price=Decimal('52.00'), stock=70, tags="Ropa, Mujer, Falda, Moda"),
    Product(name="Bermudas Cargo Hombre", description=lorem_ipsum.paragraph(), price=Decimal('42.50'), stock=140, tags="Ropa, Hombre, Bermudas, Verano"),
    Product(name="Top Deportivo Mujer Alto Impacto", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=160, tags="Ropa, Mujer, Deporte, Fitness"),
    Product(name="Calcetines Técnicos Running (Pack 3)", description=lorem_ipsum.paragraph(), price=Decimal('19.99'), stock=250, tags="Ropa, Deporte, Accesorios, Running"),
    Product(name="Traje de Baño Hombre Surf", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=95, tags="Ropa, Hombre, Bañador, Playa"),
    Product(name="Bikini Mujer Triángulo", description=lorem_ipsum.paragraph(), price=Decimal('42.90'), stock=85, tags="Ropa, Mujer, Bikini, Playa"),
    Product(name="Abrigo de Lana Clásico Hombre", description=lorem_ipsum.paragraph(), price=Decimal('180.00'), stock=50, tags="Ropa, Hombre, Abrigo, Invierno"),
    Product(name="Parka con Capucha Pelo Mujer", description=lorem_ipsum.paragraph(), price=Decimal('165.50'), stock=60, tags="Ropa, Mujer, Abrigo, Invierno"),
    Product(name="Polo Algodón Piqué Hombre", description=lorem_ipsum.paragraph(), price=Decimal('35.75'), stock=170, tags="Ropa, Hombre, Polo, Casual"),
    Product(name="Leggings Deportivos Mujer Cintura Alta", description=lorem_ipsum.paragraph(), price=Decimal('40.00'), stock=190, tags="Ropa, Mujer, Deporte, Leggings"),

    # Calzado (20 productos)
    Product(name="Zapatillas Running Neutras MaxCushion", description=lorem_ipsum.paragraph(), price=Decimal('130.99'), stock=100, tags="Calzado, Deporte, Running, Zapatillas"),
    Product(name="Zapatos de Vestir Cuero Hombre Oxford", description=lorem_ipsum.paragraph(), price=Decimal('160.00'), stock=70, tags="Calzado, Hombre, Formal, Zapatos de Cuero"),
    Product(name="Botines Chelsea Mujer Piel", description=lorem_ipsum.paragraph(), price=Decimal('110.50'), stock=90, tags="Calzado, Mujer, Botines, Moda"),
    Product(name="Sandalias Trekking Verano Unisex", description=lorem_ipsum.paragraph(), price=Decimal('75.00'), stock=120, tags="Calzado, Unisex, Sandalias, Outdoor"),
    Product(name="Zapatillas Urbanas Lona Clásicas", description=lorem_ipsum.paragraph(), price=Decimal('60.25'), stock=200, tags="Calzado, Casual, Zapatillas, Lona"),
    Product(name="Botas de Fútbol Césped Artificial", description=lorem_ipsum.paragraph(), price=Decimal('95.90'), stock=80, tags="Calzado, Deporte, Fútbol, Botas"),
    Product(name="Zapatos de Tacón Salón Mujer", description=lorem_ipsum.paragraph(), price=Decimal('85.00'), stock=60, tags="Calzado, Mujer, Tacones, Elegante"),
    Product(name="Mocasines Hombre Confort Piel", description=lorem_ipsum.paragraph(), price=Decimal('99.99'), stock=75, tags="Calzado, Hombre, Mocasines, Casual"),
    Product(name="Zapatillas Deportivas Niño Velcro", description=lorem_ipsum.paragraph(), price=Decimal('45.50'), stock=150, tags="Calzado, Infantil, Deporte, Zapatillas"),
    Product(name="Pantuflas de Casa Memory Foam", description=lorem_ipsum.paragraph(), price=Decimal('29.95'), stock=180, tags="Calzado, Hogar, Pantuflas, Confort"),
    Product(name="Botas de Agua Goma Mujer", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=0, tags="Calzado, Mujer, Botas de Agua, Lluvia"), # Stock 0
    Product(name="Zapatillas de Baloncesto Alto Rendimiento", description=lorem_ipsum.paragraph(), price=Decimal('140.75'), stock=65, tags="Calzado, Deporte, Baloncesto, Zapatillas"),
    Product(name="Alpargatas de Yute Verano", description=lorem_ipsum.paragraph(), price=Decimal('35.00'), stock=130, tags="Calzado, Verano, Alpargatas, Casual"),
    Product(name="Zapatos de Seguridad Punta de Acero", description=lorem_ipsum.paragraph(), price=Decimal('105.00'), stock=55, tags="Calzado, Trabajo, Seguridad, Botas"),
    Product(name="Bailarinas Plegables Mujer", description=lorem_ipsum.paragraph(), price=Decimal('40.90'), stock=110, tags="Calzado, Mujer, Bailarinas, Confort"),
    Product(name="Chanclas de Playa Ergonómicas", description=lorem_ipsum.paragraph(), price=Decimal('22.99'), stock=220, tags="Calzado, Playa, Chanclas, Verano"),
    Product(name="Zapatillas de Skate Resistentes", description=lorem_ipsum.paragraph(), price=Decimal('88.00'), stock=70, tags="Calzado, Deporte, Skate, Zapatillas"),
    Product(name="Botas Militares Tácticas", description=lorem_ipsum.paragraph(), price=Decimal('175.50'), stock=40, tags="Calzado, Botas, Táctico, Outdoor"),
    Product(name="Zuecos Sanitarios Profesionales", description=lorem_ipsum.paragraph(), price=Decimal('48.00'), stock=90, tags="Calzado, Trabajo, Sanitario, Zuecos"),
    Product(name="Zapatillas Minimalistas Trail Running", description=lorem_ipsum.paragraph(), price=Decimal('115.00'), stock=50, tags="Calzado, Deporte, Trail, Running"),

    # Accesorios de Moda (20 productos)
    Product(name="Bolso Tote de Cuero Mujer", description=lorem_ipsum.paragraph(), price=Decimal('140.00'), stock=60, tags="Accesorios, Moda, Bolso, Cuero, Mujer"),
    Product(name="Reloj Analógico Clásico Correa Piel", description=lorem_ipsum.paragraph(), price=Decimal('199.99'), stock=80, tags="Accesorios, Reloj, Clásico, Piel"),
    Product(name="Gafas de Sol Aviador Polarizadas", description=lorem_ipsum.paragraph(), price=Decimal('79.50'), stock=150, tags="Accesorios, Gafas de Sol, Moda, Protección UV"),
    Product(name="Cinturón de Piel Reversible Hombre", description=lorem_ipsum.paragraph(), price=Decimal('49.00'), stock=120, tags="Accesorios, Cinturón, Piel, Hombre"),
    Product(name="Bufanda de Lana Merino Unisex", description=lorem_ipsum.paragraph(), price=Decimal('65.90'), stock=100, tags="Accesorios, Bufanda, Lana, Invierno"),
    Product(name="Gorra de Béisbol Bordada", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=200, tags="Accesorios, Gorra, Casual, Moda"),
    Product(name="Collar Colgante Plata de Ley", description=lorem_ipsum.paragraph(), price=Decimal('95.75'), stock=70, tags="Accesorios, Joyería, Collar, Plata"),
    Product(name="Pulsera de Acero Inoxidable Hombre", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=90, tags="Accesorios, Joyería, Pulsera, Hombre"),
    Product(name="Pendientes de Perlas Cultivadas", description=lorem_ipsum.paragraph(), price=Decimal('120.00'), stock=50, tags="Accesorios, Joyería, Pendientes, Perlas"),
    Product(name="Cartera de Piel RFID Bloqueo", description=lorem_ipsum.paragraph(), price=Decimal('60.99'), stock=110, tags="Accesorios, Cartera, Piel, Seguridad"),
    Product(name="Pañuelo de Seda Estampado", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=130, tags="Accesorios, Pañuelo, Seda, Moda"),
    Product(name="Gemelos Elegantes para Camisa", description=lorem_ipsum.paragraph(), price=Decimal('70.50'), stock=65, tags="Accesorios, Joyería, Gemelos, Hombre"),
    Product(name="Sombrero Fedora de Fieltro", description=lorem_ipsum.paragraph(), price=Decimal('88.00'), stock=40, tags="Accesorios, Sombrero, Moda, Fieltro"),
    Product(name="Llavero de Diseño Exclusivo", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=160, tags="Accesorios, Llavero, Regalo, Diseño"),
    Product(name="Guantes de Piel Táctiles", description=lorem_ipsum.paragraph(), price=Decimal('58.99'), stock=85, tags="Accesorios, Guantes, Piel, Invierno"),
    Product(name="Bandana Multifuncional Deportiva", description=lorem_ipsum.paragraph(), price=Decimal('15.00'), stock=250, tags="Accesorios, Deporte, Bandana, Multifuncional"),
    Product(name="Set de Broches Decorativos", description=lorem_ipsum.paragraph(), price=Decimal('35.70'), stock=75, tags="Accesorios, Joyería, Broche, Decoración"),
    Product(name="Diadema Ancha Terciopelo", description=lorem_ipsum.paragraph(), price=Decimal('22.50'), stock=95, tags="Accesorios, Cabello, Diadema, Moda"),
    Product(name="Tirantes Ajustables Clásicos", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=55, tags="Accesorios, Tirantes, Moda, Clásico"),
    Product(name="Monedero Compacto Piel Mujer", description=lorem_ipsum.paragraph(), price=Decimal('39.00'), stock=140, tags="Accesorios, Monedero, Piel, Mujer"),

    # Hogar y Muebles (20 productos)
    Product(name="Sofá Modular 3 Plazas Tela Gris", description=lorem_ipsum.paragraph(), price=Decimal('799.00'), stock=15, tags="Hogar, Muebles, Sofá, Sala"),
    Product(name="Cama Doble con Almacenaje Integrado", description=lorem_ipsum.paragraph(), price=Decimal('550.50'), stock=20, tags="Hogar, Muebles, Cama, Dormitorio"),
    Product(name="Mesa de Comedor Extensible Madera Roble", description=lorem_ipsum.paragraph(), price=Decimal('420.00'), stock=25, tags="Hogar, Muebles, Mesa, Comedor"),
    Product(name="Silla de Oficina Ergonómica Malla", description=lorem_ipsum.paragraph(), price=Decimal('180.99'), stock=50, tags="Hogar, Muebles, Silla, Oficina"),
    Product(name="Estantería Librería Alta Blanca", description=lorem_ipsum.paragraph(), price=Decimal('150.00'), stock=40, tags="Hogar, Muebles, Estantería, Almacenaje"),
    Product(name="Mesa de Centro Elevable Lacada", description=lorem_ipsum.paragraph(), price=Decimal('120.75'), stock=30, tags="Hogar, Muebles, Mesa de Centro, Sala"),
    Product(name="Armario Ropero 3 Puertas Espejo", description=lorem_ipsum.paragraph(), price=Decimal('380.00'), stock=18, tags="Hogar, Muebles, Armario, Dormitorio"),
    Product(name="Sillón Relax Reclinable Manual", description=lorem_ipsum.paragraph(), price=Decimal('275.90'), stock=22, tags="Hogar, Muebles, Sillón, Confort"),
    Product(name="Escritorio Juvenil con Cajones", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=35, tags="Hogar, Muebles, Escritorio, Estudio"),
    Product(name="Zapatero Estrecho Pasillo", description=lorem_ipsum.paragraph(), price=Decimal('75.50'), stock=60, tags="Hogar, Muebles, Zapatero, Organización"),
    Product(name="Cabecero de Cama Tapizado Terciopelo", description=lorem_ipsum.paragraph(), price=Decimal('130.00'), stock=28, tags="Hogar, Muebles, Cabecero, Dormitorio"),
    Product(name="Mueble de TV Bajo con Estantes", description=lorem_ipsum.paragraph(), price=Decimal('199.95'), stock=33, tags="Hogar, Muebles, Mueble TV, Sala"),
    Product(name="Set de 4 Sillas Comedor Nórdicas", description=lorem_ipsum.paragraph(), price=Decimal('240.00'), stock=45, tags="Hogar, Muebles, Sillas, Comedor"),
    Product(name="Perchero de Pie Metálico Moderno", description=lorem_ipsum.paragraph(), price=Decimal('59.00'), stock=70, tags="Hogar, Muebles, Perchero, Organización"),
    Product(name="Cómoda 4 Cajones Madera Blanca", description=lorem_ipsum.paragraph(), price=Decimal('165.00'), stock=26, tags="Hogar, Muebles, Cómoda, Dormitorio"),
    Product(name="Banco Descalzador Entrada con Almacenaje", description=lorem_ipsum.paragraph(), price=Decimal('95.80'), stock=38, tags="Hogar, Muebles, Banco, Entrada"),
    Product(name="Puff Redondo Tejido", description=lorem_ipsum.paragraph(), price=Decimal('68.00'), stock=55, tags="Hogar, Muebles, Puff, Decoración"),
    Product(name="Mesita de Noche Flotante Minimalista", description=lorem_ipsum.paragraph(), price=Decimal('88.00'), stock=42, tags="Hogar, Muebles, Mesita de Noche, Dormitorio"),
    Product(name="Paragüero Diseño Moderno", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=0, tags="Hogar, Muebles, Paragüero, Entrada"), # Stock 0
    Product(name="Carrito Auxiliar Cocina/Baño Ruedas", description=lorem_ipsum.paragraph(), price=Decimal('72.99'), stock=65, tags="Hogar, Muebles, Carrito, Almacenaje"),

    # Cocina y Comedor (20 productos)
    Product(name="Cafetera Espresso Automática", description=lorem_ipsum.paragraph(), price=Decimal('299.00'), stock=40, tags="Cocina, Electrodoméstico, Café, Cafetera"),
    Product(name="Robot de Cocina Multifunción ProChef", description=lorem_ipsum.paragraph(), price=Decimal('450.99'), stock=30, tags="Cocina, Electrodoméstico, Robot Cocina, Multifunción"),
    Product(name="Licuadora de Vaso Alta Potencia", description=lorem_ipsum.paragraph(), price=Decimal('89.90'), stock=70, tags="Cocina, Electrodoméstico, Licuadora, Batidos"),
    Product(name="Batería de Cocina Antiadherente 8 Piezas", description=lorem_ipsum.paragraph(), price=Decimal('150.00'), stock=50, tags="Cocina, Utensilios, Batería Cocina, Sartenes"),
    Product(name="Juego de Cuchillos Profesionales con Taco", description=lorem_ipsum.paragraph(), price=Decimal('120.50'), stock=60, tags="Cocina, Utensilios, Cuchillos, Chef"),
    Product(name="Vajilla Completa Porcelana 18 Piezas", description=lorem_ipsum.paragraph(), price=Decimal('99.75'), stock=45, tags="Cocina, Vajilla, Porcelana, Comedor"),
    Product(name="Freidora de Aire sin Aceite 5L", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=80, tags="Cocina, Electrodoméstico, Freidora Aire, Saludable"),
    Product(name="Tostadora Ranura Ancha Vintage", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=100, tags="Cocina, Electrodoméstico, Tostadora, Desayuno"),
    Product(name="Hervidor de Agua Eléctrico Inox", description=lorem_ipsum.paragraph(), price=Decimal('35.99'), stock=120, tags="Cocina, Electrodoméstico, Hervidor, Té"),
    Product(name="Microondas con Grill Integrado 20L", description=lorem_ipsum.paragraph(), price=Decimal('130.00'), stock=55, tags="Cocina, Electrodoméstico, Microondas, Grill"),
    Product(name="Set de Repostería Moldes Silicona", description=lorem_ipsum.paragraph(), price=Decimal('39.95'), stock=90, tags="Cocina, Repostería, Moldes, Utensilios"),
    Product(name="Báscula de Cocina Digital Precisión", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=150, tags="Cocina, Utensilios, Báscula, Medición"),
    Product(name="Tabla de Cortar Bambú Extragrande", description=lorem_ipsum.paragraph(), price=Decimal('28.50'), stock=110, tags="Cocina, Utensilios, Tabla Cortar, Bambú"),
    Product(name="Set 6 Copas de Vino Cristal Fino", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=75, tags="Cocina, Cristalería, Copas, Vino"),
    Product(name="Exprimidor de Cítricos Eléctrico", description=lorem_ipsum.paragraph(), price=Decimal('32.90'), stock=85, tags="Cocina, Electrodoméstico, Exprimidor, Zumo"),
    Product(name="Wok Acero Carbono Tradicional", description=lorem_ipsum.paragraph(), price=Decimal('48.00'), stock=65, tags="Cocina, Utensilios, Wok, Asiática"),
    Product(name="Rallador Multiusos con Contenedor", description=lorem_ipsum.paragraph(), price=Decimal('25.75'), stock=130, tags="Cocina, Utensilios, Rallador, Verduras"),
    Product(name="Panificadora Automática Programable", description=lorem_ipsum.paragraph(), price=Decimal('160.00'), stock=35, tags="Cocina, Electrodoméstico, Panificadora, Pan Casero"),
    Product(name="Molinillo de Café Eléctrico Cuchillas", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=95, tags="Cocina, Electrodoméstico, Café, Molinillo"),
    Product(name="Set de Cubiertos Acero Inoxidable 24 Piezas", description=lorem_ipsum.paragraph(), price=Decimal('70.99'), stock=100, tags="Cocina, Cubertería, Acero Inoxidable, Comedor"),

    # Decoración del Hogar (20 productos)
    Product(name="Lámpara de Pie Trípode Madera Nórdica", description=lorem_ipsum.paragraph(), price=Decimal('119.00'), stock=30, tags="Decoración, Iluminación, Lámpara, Nórdico"),
    Product(name="Alfombra Salón Pelo Largo Shaggy Gris", description=lorem_ipsum.paragraph(), price=Decimal('89.50'), stock=40, tags="Decoración, Textil, Alfombra, Salón"),
    Product(name="Set de 3 Marcos Fotos Pared Negros", description=lorem_ipsum.paragraph(), price=Decimal('29.99'), stock=150, tags="Decoración, Marcos, Fotos, Pared"),
    Product(name="Espejo Redondo Marco Metálico Dorado", description=lorem_ipsum.paragraph(), price=Decimal('75.00'), stock=50, tags="Decoración, Espejo, Moderno, Pared"),
    Product(name="Cojín Terciopelo Mostaza 45x45cm", description=lorem_ipsum.paragraph(), price=Decimal('18.90'), stock=200, tags="Decoración, Textil, Cojín, Sofá"),
    Product(name="Cortinas Opacas Salón (2 Paneles)", description=lorem_ipsum.paragraph(), price=Decimal('55.75'), stock=70, tags="Decoración, Textil, Cortinas, Opacas"),
    Product(name="Jarrón Cerámica Diseño Abstracto", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=60, tags="Decoración, Jarrón, Cerámica, Adorno"),
    Product(name="Velas Aromáticas Set Regalo (Lavanda, Vainilla, Sándalo)", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=120, tags="Decoración, Velas, Aromaterapia, Regalo"),
    Product(name="Planta Artificial Colgante Hiedra", description=lorem_ipsum.paragraph(), price=Decimal('25.50'), stock=90, tags="Decoración, Plantas Artificiales, Interior, Verde"),
    Product(name="Reloj de Pared Grande Silencioso Vintage", description=lorem_ipsum.paragraph(), price=Decimal('60.00'), stock=80, tags="Decoración, Reloj de Pared, Vintage, Silencioso"),
    Product(name="Manta Suave Franela Sofá/Cama", description=lorem_ipsum.paragraph(), price=Decimal('38.99'), stock=180, tags="Decoración, Textil, Manta, Confort"),
    Product(name="Cuadro Lienzo Paisaje Abstracto Moderno", description=lorem_ipsum.paragraph(), price=Decimal('95.00'), stock=35, tags="Decoración, Arte, Cuadro, Lienzo"),
    Product(name="Guirnalda Luces LED Exterior Solar", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=100, tags="Decoración, Iluminación, Exterior, Solar"),
    Product(name="Cesta Almacenaje Mimbre con Tapa", description=lorem_ipsum.paragraph(), price=Decimal('36.70'), stock=75, tags="Decoración, Almacenaje, Cesta, Mimbre"),
    Product(name="Felpudo Entrada Original Coco", description=lorem_ipsum.paragraph(), price=Decimal('19.95'), stock=130, tags="Decoración, Entrada, Felpudo, Original"),
    Product(name="Figura Decorativa Elefante Resina", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=65, tags="Decoración, Adorno, Figura, Animales"),
    Product(name="Camino de Mesa Lino Bordado", description=lorem_ipsum.paragraph(), price=Decimal('27.00'), stock=85, tags="Decoración, Textil, Camino de Mesa, Comedor"),
    Product(name="Portavelas Cristal Geométrico (Set 2)", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=95, tags="Decoración, Portavelas, Cristal, Moderno"),
    Product(name="Estor Enrollable Translúcido Blanco", description=lorem_ipsum.paragraph(), price=Decimal('40.90'), stock=110, tags="Decoración, Textil, Estor, Ventana"),
    Product(name="Vinilo Decorativo Pared Frase Inspiradora", description=lorem_ipsum.paragraph(), price=Decimal('15.99'), stock=0, tags="Decoración, Vinilo, Pared, Frases"), # Stock 0

    # Jardinería (20 productos)
    Product(name="Set Herramientas Jardín Acero Inox (Pala, Rastrillo, Tijeras)", description=lorem_ipsum.paragraph(), price=Decimal('49.99'), stock=70, tags="Jardinería, Herramientas, Set, Acero"),
    Product(name="Manguera Extensible Riego 30m con Pistola", description=lorem_ipsum.paragraph(), price=Decimal('35.50'), stock=90, tags="Jardinería, Riego, Manguera, Extensible"),
    Product(name="Macetero Autorriego Diseño Moderno", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=120, tags="Jardinería, Macetas, Autorriego, Plantas"),
    Product(name="Semillas Ecológicas Huerto Urbano (Pack Variado)", description=lorem_ipsum.paragraph(), price=Decimal('19.75'), stock=200, tags="Jardinería, Semillas, Huerto, Ecológico"),
    Product(name="Guantes de Jardinería Piel Reforzados", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=150, tags="Jardinería, Protección, Guantes, Piel"),
    Product(name="Barbacoa Portátil Carbón Plegable", description=lorem_ipsum.paragraph(), price=Decimal('75.90'), stock=50, tags="Jardinería, Exterior, Barbacoa, Portátil"),
    Product(name="Sustrato Universal Plantas 50L", description=lorem_ipsum.paragraph(), price=Decimal('15.00'), stock=100, tags="Jardinería, Sustrato, Plantas, Tierra"),
    Product(name="Ahuyentador Solar Ultrasónico Animales", description=lorem_ipsum.paragraph(), price=Decimal('30.99'), stock=80, tags="Jardinería, Control Plagas, Solar, Ultrasónico"),
    Product(name="Tumbona Plegable Jardín Aluminio Textileno", description=lorem_ipsum.paragraph(), price=Decimal('95.00'), stock=40, tags="Jardinería, Muebles Exterior, Tumbona, Relax"),
    Product(name="Lámpara Solar LED Estaca Jardín (Pack 4)", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=110, tags="Jardinería, Iluminación Exterior, Solar, LED"),
    Product(name="Programador Riego Automático Digital", description=lorem_ipsum.paragraph(), price=Decimal('55.80'), stock=60, tags="Jardinería, Riego, Automático, Programador"),
    Product(name="Césped Artificial Realista 1x5m", description=lorem_ipsum.paragraph(), price=Decimal('65.00'), stock=30, tags="Jardinería, Decoración Exterior, Césped Artificial"),
    Product(name="Invernadero Pequeño Terraza PVC", description=lorem_ipsum.paragraph(), price=Decimal('88.99'), stock=25, tags="Jardinería, Cultivo, Invernadero, Terraza"),
    Product(name="Compostador Doméstico 300L", description=lorem_ipsum.paragraph(), price=Decimal('105.00'), stock=20, tags="Jardinería, Compostaje, Orgánico, Reciclaje"),
    Product(name="Carretilla Plegable Jardín 75L", description=lorem_ipsum.paragraph(), price=Decimal('62.50'), stock=35, tags="Jardinería, Transporte, Carretilla, Plegable"),
    Product(name="Arco Decorativo para Rosales Metal", description=lorem_ipsum.paragraph(), price=Decimal('49.00'), stock=45, tags="Jardinería, Decoración Exterior, Arco, Plantas Trepadoras"),
    Product(name="Hamaca Colgante Algodón con Soporte", description=lorem_ipsum.paragraph(), price=Decimal('130.70'), stock=15, tags="Jardinería, Muebles Exterior, Hamaca, Relax"),
    Product(name="Bordura Delimitadora Jardín Flexible", description=lorem_ipsum.paragraph(), price=Decimal('18.00'), stock=130, tags="Jardinería, Decoración Exterior, Bordura, Delimitador"),
    Product(name="Fuente Solar Decorativa Pájaros", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=55, tags="Jardinería, Decoración Exterior, Fuente, Solar"),
    Product(name="Tijeras de Podar Profesionales Bypass", description=lorem_ipsum.paragraph(), price=Decimal('33.99'), stock=95, tags="Jardinería, Herramientas, Poda, Tijeras"),

    # Deportes y Fitness (20 productos)
    Product(name="Mancuernas Ajustables Set 20kg", description=lorem_ipsum.paragraph(), price=Decimal('120.00'), stock=60, tags="Deportes, Fitness, Pesas, Musculación"),
    Product(name="Esterilla Yoga Antideslizante Ecológica", description=lorem_ipsum.paragraph(), price=Decimal('35.99'), stock=150, tags="Deportes, Yoga, Pilates, Esterilla"),
    Product(name="Bicicleta Estática Plegable con Resistencia Magnética", description=lorem_ipsum.paragraph(), price=Decimal('199.50'), stock=40, tags="Deportes, Fitness, Cardio, Bicicleta Estática"),
    Product(name="Comba de Saltar Rápida Rodamientos", description=lorem_ipsum.paragraph(), price=Decimal('15.75'), stock=200, tags="Deportes, Fitness, Cardio, Comba"),
    Product(name="Bandas Elásticas Resistencia (Set 5)", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=180, tags="Deportes, Fitness, Resistencia, Entrenamiento"),
    Product(name="Rodillo Abdominales Rueda Doble", description=lorem_ipsum.paragraph(), price=Decimal('22.90'), stock=120, tags="Deportes, Fitness, Abdominales, Core"),
    Product(name="Pulsómetro de Muñeca GPS Integrado", description=lorem_ipsum.paragraph(), price=Decimal('180.00'), stock=70, tags="Deportes, Running, Ciclismo, Pulsómetro"),
    Product(name="Balón de Fútbol Oficial Tamaño 5", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=100, tags="Deportes, Fútbol, Balón, Equipo"),
    Product(name="Raqueta de Tenis Carbono Ligera", description=lorem_ipsum.paragraph(), price=Decimal('95.50'), stock=50, tags="Deportes, Tenis, Raqueta, Equipamiento"),
    Product(name="Guantes de Boxeo Piel Sintética 12oz", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=80, tags="Deportes, Boxeo, Guantes, Protección"),
    Product(name="Botella de Agua Deportiva Acero Inox 1L", description=lorem_ipsum.paragraph(), price=Decimal('28.99'), stock=130, tags="Deportes, Hidratación, Botella, Acero"),
    Product(name="Mochila Deportiva Gimnasio Compartimento Zapatillas", description=lorem_ipsum.paragraph(), price=Decimal('39.00'), stock=90, tags="Deportes, Accesorios, Mochila, Gimnasio"),
    Product(name="Pelota Pilates Fitball Antiexplosión", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=110, tags="Deportes, Pilates, Fitness, Pelota"),
    Product(name="Tabla de Equilibrio Madera Balance Board", description=lorem_ipsum.paragraph(), price=Decimal('55.70'), stock=65, tags="Deportes, Fitness, Equilibrio, Rehabilitación"),
    Product(name="Anillas Gimnasia Madera Correas Ajustables", description=lorem_ipsum.paragraph(), price=Decimal('48.00'), stock=55, tags="Deportes, Calistenia, Gimnasia, Anillas"),
    Product(name="Stepper Fitness con Bandas Elásticas", description=lorem_ipsum.paragraph(), price=Decimal('70.90'), stock=45, tags="Deportes, Fitness, Cardio, Stepper"),
    Product(name="Gafas de Natación Antivaho Protección UV", description=lorem_ipsum.paragraph(), price=Decimal('18.50'), stock=160, tags="Deportes, Natación, Gafas, Accesorios"),
    Product(name="Cinta de Correr Plegable Eléctrica", description=lorem_ipsum.paragraph(), price=Decimal('450.00'), stock=25, tags="Deportes, Fitness, Cardio, Cinta Correr"),
    Product(name="Saco de Boxeo Pesado con Soporte", description=lorem_ipsum.paragraph(), price=Decimal('160.00'), stock=0, tags="Deportes, Boxeo, Saco, Entrenamiento"), # Stock 0
    Product(name="Banca de Musculación Ajustable Multiposición", description=lorem_ipsum.paragraph(), price=Decimal('140.99'), stock=30, tags="Deportes, Fitness, Musculación, Banca"),

    # Aire Libre y Camping (20 productos)
    Product(name="Tienda de Campaña Familiar 4 Personas Impermeable", description=lorem_ipsum.paragraph(), price=Decimal('180.00'), stock=30, tags="Aire Libre, Camping, Tienda, Familiar"),
    Product(name="Saco de Dormir Ligero 3 Estaciones", description=lorem_ipsum.paragraph(), price=Decimal('65.90'), stock=70, tags="Aire Libre, Camping, Saco Dormir, Ligero"),
    Product(name="Mochila Trekking 60L Espalda Ventilada", description=lorem_ipsum.paragraph(), price=Decimal('110.50'), stock=50, tags="Aire Libre, Trekking, Mochila, Montaña"),
    Product(name="Colchón Hinchable Doble Camping", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=80, tags="Aire Libre, Camping, Colchón, Confort"),
    Product(name="Hornillo de Gas Portátil para Camping", description=lorem_ipsum.paragraph(), price=Decimal('32.75'), stock=100, tags="Aire Libre, Camping, Cocina, Hornillo"),
    Product(name="Linterna Frontal LED Recargable Alta Potencia", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=120, tags="Aire Libre, Iluminación, Linterna, Recargable"),
    Product(name="Set de Cocina Camping Aluminio Anodizado", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=60, tags="Aire Libre, Camping, Utensilios Cocina, Ligero"),
    Product(name="Silla Plegable Camping Compacta", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=150, tags="Aire Libre, Camping, Silla, Plegable"),
    Product(name="Bastones de Senderismo Telescópicos Carbono", description=lorem_ipsum.paragraph(), price=Decimal('70.00'), stock=90, tags="Aire Libre, Senderismo, Bastones, Carbono"),
    Product(name="Nevera Portátil Rígida 25L", description=lorem_ipsum.paragraph(), price=Decimal('60.90'), stock=40, tags="Aire Libre, Camping, Nevera, Conservación"),
    Product(name="Filtro de Agua Portátil Supervivencia", description=lorem_ipsum.paragraph(), price=Decimal('38.50'), stock=75, tags="Aire Libre, Supervivencia, Agua, Filtro"),
    Product(name="Hamaca de Nylon Ultraligera con Mosquitera", description=lorem_ipsum.paragraph(), price=Decimal('49.00'), stock=65, tags="Aire Libre, Camping, Hamaca, Mosquitera"),
    Product(name="Ducha Solar Portátil 20L", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=85, tags="Aire Libre, Camping, Higiene, Ducha Solar"),
    Product(name="Mesa Plegable Camping Aluminio Ligera", description=lorem_ipsum.paragraph(), price=Decimal('58.00'), stock=55, tags="Aire Libre, Camping, Mesa, Plegable"),
    Product(name="Prismáticos Compactos Observación Aves 10x42", description=lorem_ipsum.paragraph(), price=Decimal('95.99'), stock=45, tags="Aire Libre, Observación, Prismáticos, Naturaleza"),
    Product(name="Cuerda de Escalada Dinámica 60m", description=lorem_ipsum.paragraph(), price=Decimal('150.00'), stock=20, tags="Aire Libre, Escalada, Cuerda, Seguridad"),
    Product(name="Kit de Primeros Auxilios Completo Outdoor", description=lorem_ipsum.paragraph(), price=Decimal('33.70'), stock=110, tags="Aire Libre, Seguridad, Primeros Auxilios, Emergencia"),
    Product(name="GPS de Mano Navegación Montaña", description=lorem_ipsum.paragraph(), price=Decimal('220.00'), stock=25, tags="Aire Libre, Navegación, GPS, Montaña"),
    Product(name="Navaja Multiusos Suiza Original", description=lorem_ipsum.paragraph(), price=Decimal('42.90'), stock=130, tags="Aire Libre, Herramientas, Navaja, Multiusos"),
    Product(name="Manta de Picnic Impermeable Extragrande", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=100, tags="Aire Libre, Picnic, Manta, Impermeable"),

    # Juguetes y Juegos (20 productos)
    Product(name="Puzzle 1000 Piezas Paisaje Fantástico", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=120, tags="Juguetes, Juegos de Mesa, Puzzle, Adultos"),
    Product(name="Juego de Mesa Estrategia Colonos Pro", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=70, tags="Juguetes, Juegos de Mesa, Estrategia, Familiar"),
    Product(name="Muñeca Bebé Realista con Accesorios", description=lorem_ipsum.paragraph(), price=Decimal('48.50'), stock=90, tags="Juguetes, Muñecas, Infantil, Realista"),
    Product(name="Coche Teledirigido Todoterreno RC", description=lorem_ipsum.paragraph(), price=Decimal('65.75'), stock=60, tags="Juguetes, Vehículos, Teledirigido, RC"),
    Product(name="Bloques de Construcción Creativos (500 piezas)", description=lorem_ipsum.paragraph(), price=Decimal('39.00'), stock=150, tags="Juguetes, Construcción, Educativo, Infantil"),
    Product(name="Peluche Oso Gigante Suave 100cm", description=lorem_ipsum.paragraph(), price=Decimal('70.90'), stock=50, tags="Juguetes, Peluches, Infantil, Regalo"),
    Product(name="Cometa Acrobática Profesional 2 Hilos", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=80, tags="Juguetes, Aire Libre, Cometa, Acrobática"),
    Product(name="Set Figuras de Acción Superhéroes Colección", description=lorem_ipsum.paragraph(), price=Decimal('59.95'), stock=100, tags="Juguetes, Figuras Acción, Coleccionismo, Superhéroes"),
    Product(name="Juego Educativo Ciencia Experimentos Niños", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=110, tags="Juguetes, Educativo, Ciencia, Infantil"),
    Product(name="Patinete 3 Ruedas Infantil Luces LED", description=lorem_ipsum.paragraph(), price=Decimal('52.00'), stock=75, tags="Juguetes, Aire Libre, Patinete, Infantil"),
    Product(name="Casa de Muñecas Madera con Muebles", description=lorem_ipsum.paragraph(), price=Decimal('120.00'), stock=30, tags="Juguetes, Muñecas, Casa de Muñecas, Madera"),
    Product(name="Tren Eléctrico Clásico con Vías", description=lorem_ipsum.paragraph(), price=Decimal('88.99'), stock=40, tags="Juguetes, Vehículos, Tren, Clásico"),
    Product(name="Disfraz Infantil Princesa/Pirata (Varias Tallas)", description=lorem_ipsum.paragraph(), price=Decimal('35.50'), stock=130, tags="Juguetes, Disfraces, Infantil, Fiesta"),
    Product(name="Juego de Magia Profesional para Niños", description=lorem_ipsum.paragraph(), price=Decimal('29.00'), stock=95, tags="Juguetes, Magia, Educativo, Infantil"),
    Product(name="Robot Interactivo Programable Educativo", description=lorem_ipsum.paragraph(), price=Decimal('99.00'), stock=0, tags="Juguetes, Robótica, Educativo, Programación"), # Stock 0
    Product(name="Triciclo Evolutivo Bebé con Capota", description=lorem_ipsum.paragraph(), price=Decimal('110.70'), stock=35, tags="Juguetes, Bebés, Triciclo, Exterior"),
    Product(name="Juego de Cartas Familiar Rápido y Divertido", description=lorem_ipsum.paragraph(), price=Decimal('15.95'), stock=200, tags="Juguetes, Juegos de Mesa, Cartas, Familiar"),
    Product(name="Pizarra Magnética Infantil Doble Cara", description=lorem_ipsum.paragraph(), price=Decimal('40.00'), stock=85, tags="Juguetes, Educativo, Pizarra, Infantil"),
    Product(name="Dron Pequeño para Niños Fácil de Volar", description=lorem_ipsum.paragraph(), price=Decimal('49.90'), stock=65, tags="Juguetes, Dron, Infantil, Tecnológico"),
    Product(name="Plastilina Modelar Set Creativo (24 colores)", description=lorem_ipsum.paragraph(), price=Decimal('18.99'), stock=160, tags="Juguetes, Manualidades, Plastilina, Creativo"),

    # Libros (20 productos)
    Product(name="Novela Best Seller Ficción Histórica", description=lorem_ipsum.paragraph(), price=Decimal('22.95'), stock=250, tags="Libros, Ficción, Novela, Best Seller"),
    Product(name="Ensayo Sobre Filosofía Contemporánea", description=lorem_ipsum.paragraph(), price=Decimal('19.50'), stock=100, tags="Libros, No Ficción, Ensayo, Filosofía"),
    Product(name="Libro Infantil Ilustrado Animales de la Granja", description=lorem_ipsum.paragraph(), price=Decimal('15.00'), stock=300, tags="Libros, Infantil, Ilustrado, Animales"),
    Product(name="Manual de Programación Python Avanzado", description=lorem_ipsum.paragraph(), price=Decimal('45.75'), stock=120, tags="Libros, Informática, Programación, Educativo"),
    Product(name="Libro de Cocina Recetas del Mundo", description=lorem_ipsum.paragraph(), price=Decimal('30.90'), stock=180, tags="Libros, Cocina, Recetas, Gastronomía"),
    Product(name="Biografía Inspiradora Emprendedor Éxito", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=90, tags="Libros, No Ficción, Biografía, Inspirador"),
    Product(name="Cómic Novela Gráfica Aventura Épica", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=110, tags="Libros, Cómic, Novela Gráfica, Aventura"),
    Product(name="Libro de Poesía Clásica Universal", description=lorem_ipsum.paragraph(), price=Decimal('18.99'), stock=130, tags="Libros, Poesía, Clásicos, Literatura"),
    Product(name="Guía de Viaje Completa Europa 2025", description=lorem_ipsum.paragraph(), price=Decimal('35.00'), stock=70, tags="Libros, Viajes, Guías, Turismo"),
    Product(name="Libro de Arte Grandes Maestros del Renacimiento", description=lorem_ipsum.paragraph(), price=Decimal('55.50'), stock=60, tags="Libros, Arte, Historia del Arte, Renacimiento"),
    Product(name="Thriller Psicológico Bestseller Internacional", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=200, tags="Libros, Ficción, Thriller, Misterio"),
    Product(name="Libro de Cuentos Cortos para Dormir Niños", description=lorem_ipsum.paragraph(), price=Decimal('16.95'), stock=220, tags="Libros, Infantil, Cuentos, Dormir"),
    Product(name="Diccionario Bilingüe Inglés-Español Completo", description=lorem_ipsum.paragraph(), price=Decimal('29.90'), stock=150, tags="Libros, Referencia, Diccionario, Idiomas"),
    Product(name="Libro de Autoayuda Desarrollo Personal", description=lorem_ipsum.paragraph(), price=Decimal('21.00'), stock=170, tags="Libros, Autoayuda, Psicología, Bienestar"),
    Product(name="Saga Fantasía Juvenil (Volumen 1)", description=lorem_ipsum.paragraph(), price=Decimal('19.99'), stock=190, tags="Libros, Juvenil, Fantasía, Saga"),
    Product(name="Libro de Historia Antigua Civilizaciones", description=lorem_ipsum.paragraph(), price=Decimal('38.70'), stock=80, tags="Libros, No Ficción, Historia, Antigüedad"),
    Product(name="Manualidades Creativas para Niños Papel y Cartón", description=lorem_ipsum.paragraph(), price=Decimal('17.50'), stock=140, tags="Libros, Infantil, Manualidades, Creatividad"),
    Product(name="Libro de Fotografía Composición y Técnica", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=75, tags="Libros, Fotografía, Técnica, Arte Visual"),
    Product(name="Clásico de la Literatura Universal Edición Comentada", description=lorem_ipsum.paragraph(), price=Decimal('26.80'), stock=95, tags="Libros, Clásicos, Literatura, Edición Especial"),
    Product(name="Libro Actividades Verano Niños (Juegos, Pasatiempos)", description=lorem_ipsum.paragraph(), price=Decimal('12.99'), stock=280, tags="Libros, Infantil, Actividades, Verano"),

    # Música (20 productos)
    Product(name="Guitarra Acústica Kit Principiante (Funda, Púas, Afinador)", description=lorem_ipsum.paragraph(), price=Decimal('150.00'), stock=50, tags="Música, Instrumentos, Guitarra, Principiante"),
    Product(name="Teclado Electrónico 61 Teclas Sensitivas", description=lorem_ipsum.paragraph(), price=Decimal('199.90'), stock=40, tags="Música, Instrumentos, Teclado, Piano"),
    Product(name="Vinilo Edición Limitada Álbum Clásico Rock", description=lorem_ipsum.paragraph(), price=Decimal('45.50'), stock=100, tags="Música, Vinilos, Rock, Coleccionismo"),
    Product(name="Ukelele Soprano Caoba con Funda", description=lorem_ipsum.paragraph(), price=Decimal('65.00'), stock=80, tags="Música, Instrumentos, Ukelele, Cuerda"),
    Product(name="Auriculares de Estudio Profesionales Monitorización", description=lorem_ipsum.paragraph(), price=Decimal('120.75'), stock=60, tags="Música, Accesorios, Audio, Estudio"),
    Product(name="Batería Electrónica Compacta Pads Sensibles", description=lorem_ipsum.paragraph(), price=Decimal('350.00'), stock=25, tags="Música, Instrumentos, Batería, Electrónica"),
    Product(name="Micrófono Condensador USB para Grabación Voz/Podcast", description=lorem_ipsum.paragraph(), price=Decimal('99.00'), stock=70, tags="Música, Accesorios, Grabación, Micrófono"),
    Product(name="Armónica Diatónica Blues en Do", description=lorem_ipsum.paragraph(), price=Decimal('30.99'), stock=120, tags="Música, Instrumentos, Armónica, Blues"),
    Product(name="Altavoces Monitores de Estudio Activos (Par)", description=lorem_ipsum.paragraph(), price=Decimal('280.00'), stock=30, tags="Música, Audio, Monitores, Estudio"),
    Product(name="CD Box Set Compilación Grandes Éxitos Pop", description=lorem_ipsum.paragraph(), price=Decimal('59.95'), stock=90, tags="Música, CDs, Pop, Compilación"),
    Product(name="Violín 4/4 Kit Estudiante con Estuche y Arco", description=lorem_ipsum.paragraph(), price=Decimal('180.00'), stock=35, tags="Música, Instrumentos, Violín, Orquesta"),
    Product(name="Pedal Efectos Guitarra Distorsión Clásica", description=lorem_ipsum.paragraph(), price=Decimal('75.00'), stock=0, tags="Música, Accesorios, Guitarra, Efectos"), # Stock 0
    Product(name="Atril Plegable Partituras Metálico", description=lorem_ipsum.paragraph(), price=Decimal('22.50'), stock=150, tags="Música, Accesorios, Atril, Partituras"),
    Product(name="Cajón Flamenco Profesional Abedul", description=lorem_ipsum.paragraph(), price=Decimal('130.80'), stock=45, tags="Música, Instrumentos, Percusión, Flamenco"),
    Product(name="Interfaz de Audio USB 2 Canales Grabación", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=55, tags="Música, Accesorios, Grabación, Interfaz Audio"),
    Product(name="Correa Guitarra/Bajo Piel Acolchada", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=110, tags="Música, Accesorios, Guitarra, Correa"),
    Product(name="Flauta Dulce Soprano Barroca Madera", description=lorem_ipsum.paragraph(), price=Decimal('42.90'), stock=75, tags="Música, Instrumentos, Flauta, Viento"),
    Product(name="Metrónomo Digital Compacto Afinador", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=100, tags="Música, Accesorios, Metrónomo, Afinador"),
    Product(name="Libro Partituras Piano Fácil Clásicos Populares", description=lorem_ipsum.paragraph(), price=Decimal('19.99'), stock=130, tags="Música, Partituras, Piano, Educativo"),
    Product(name="Mesa de Mezclas DJ Compacta 2 Canales", description=lorem_ipsum.paragraph(), price=Decimal('165.00'), stock=20, tags="Música, DJ, Mezclador, Electrónica"),

    # Películas y Series TV (10 productos - categoría más pequeña)
    Product(name="Blu-ray Película Clásica Ciencia Ficción Ed. Coleccionista", description=lorem_ipsum.paragraph(), price=Decimal('29.99'), stock=80, tags="Películas, Blu-ray, Ciencia Ficción, Coleccionista"),
    Product(name="DVD Serie Completa Drama Histórico (Temporadas 1-5)", description=lorem_ipsum.paragraph(), price=Decimal('75.50'), stock=50, tags="Series TV, DVD, Drama, Completa"),
    Product(name="Película Animada Infantil Éxito Taquilla (Blu-ray + DVD)", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=120, tags="Películas, Infantil, Animación, Blu-ray"),
    Product(name="Box Set Trilogía Acción Aventuras 4K UHD", description=lorem_ipsum.paragraph(), price=Decimal('55.75'), stock=60, tags="Películas, 4K UHD, Acción, Trilogía"),
    Product(name="Serie Comedia TV Clásica Restaurada (DVD)", description=lorem_ipsum.paragraph(), price=Decimal('40.00'), stock=70, tags="Series TV, Comedia, Clásica, DVD"),
    Product(name="Documental Naturaleza Narrado (Blu-ray)", description=lorem_ipsum.paragraph(), price=Decimal('22.90'), stock=90, tags="Películas, Documental, Naturaleza, Blu-ray"),
    Product(name="Película de Terror Independiente (DVD)", description=lorem_ipsum.paragraph(), price=Decimal('18.00'), stock=100, tags="Películas, Terror, Independiente, DVD"),
    Product(name="Serie Anime Popular Temporada 1 (Blu-ray)", description=lorem_ipsum.paragraph(), price=Decimal('35.95'), stock=75, tags="Series TV, Anime, Blu-ray, Animación Japonesa"),
    Product(name="Concierto Música Legendaria en Vivo (Blu-ray)", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=65, tags="Música, Concierto, Blu-ray, En Vivo"),
    Product(name="Colección Películas Director Famoso (5 Películas DVD)", description=lorem_ipsum.paragraph(), price=Decimal('60.99'), stock=45, tags="Películas, Colección, Director, DVD"),

    # Software y Videojuegos (20 productos)
    Product(name="Videojuego AAA Acción Aventura PS5/XBOX", description=lorem_ipsum.paragraph(), price=Decimal('69.99'), stock=150, tags="Videojuegos, PS5, XBOX, Acción, Aventura"),
    Product(name="Software Edición Fotográfica Profesional Licencia Anual", description=lorem_ipsum.paragraph(), price=Decimal('120.00'), stock=200, tags="Software, Fotografía, Edición, Profesional"),
    Product(name="Videojuego Rol Fantasía Épica PC (Clave Digital)", description=lorem_ipsum.paragraph(), price=Decimal('59.95'), stock=300, tags="Videojuegos, PC, Rol, Fantasía"),
    Product(name="Antivirus Completo multidispositivo 1 Año", description=lorem_ipsum.paragraph(), price=Decimal('49.50'), stock=250, tags="Software, Seguridad, Antivirus, Protección"),
    Product(name="Videojuego Simulación Estratégica Nintendo Switch", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=100, tags="Videojuegos, Nintendo Switch, Simulación, Estrategia"),
    Product(name="Software Diseño Gráfico Vectorial Suscripción Mensual", description=lorem_ipsum.paragraph(), price=Decimal('25.75'), stock=180, tags="Software, Diseño Gráfico, Vectorial, Creativo"),
    Product(name="Videojuego Deportivo Fútbol/Baloncesto Última Edición", description=lorem_ipsum.paragraph(), price=Decimal('65.90'), stock=120, tags="Videojuegos, Deportes, Fútbol, Baloncesto"),
    Product(name="Suite Ofimática Completa Licencia Perpetua", description=lorem_ipsum.paragraph(), price=Decimal('150.00'), stock=160, tags="Software, Ofimática, Productividad, Trabajo"),
    Product(name="Videojuego Indie Aclamado Plataformas Puzzle", description=lorem_ipsum.paragraph(), price=Decimal('19.99'), stock=220, tags="Videojuegos, Indie, Plataformas, Puzzle"),
    Product(name="Software Aprendizaje Idiomas Interactivo (Pack Completo)", description=lorem_ipsum.paragraph(), price=Decimal('99.00'), stock=130, tags="Software, Educativo, Idiomas, Aprendizaje"),
    Product(name="Videojuego Carreras Realista VR Compatible", description=lorem_ipsum.paragraph(), price=Decimal('62.00'), stock=80, tags="Videojuegos, Carreras, Simulación, VR"),
    Product(name="Software Edición Video Semiprofesional", description=lorem_ipsum.paragraph(), price=Decimal('79.90'), stock=110, tags="Software, Video, Edición, Creatividad"),
    Product(name="Tarjeta Prepago Saldo Tienda Videojuegos ($20)", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=500, tags="Videojuegos, Tarjeta Regalo, Digital, Saldo"),
    Product(name="Juego Familiar Multijugador Fiesta Switch", description=lorem_ipsum.paragraph(), price=Decimal('49.99'), stock=90, tags="Videojuegos, Nintendo Switch, Familiar, Multijugador"),
    Product(name="Software Contabilidad Pequeña Empresa", description=lorem_ipsum.paragraph(), price=Decimal('199.00'), stock=70, tags="Software, Negocios, Contabilidad, Finanzas"),
    Product(name="Expansión Videojuego Popular (Requiere Juego Base)", description=lorem_ipsum.paragraph(), price=Decimal('29.95'), stock=140, tags="Videojuegos, DLC, Expansión, Contenido Adicional"),
    Product(name="Videojuego Lucha Clásico Remasterizado", description=lorem_ipsum.paragraph(), price=Decimal('39.99'), stock=0, tags="Videojuegos, Lucha, Clásico, Remaster"), # Stock 0
    Product(name="Software VPN Seguridad y Privacidad Online (1 Año)", description=lorem_ipsum.paragraph(), price=Decimal('55.80'), stock=190, tags="Software, Seguridad, VPN, Privacidad"),
    Product(name="Videojuego Construcción Mundo Abierto Creativo", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=280, tags="Videojuegos, Construcción, Creativo, Mundo Abierto"),
    Product(name="Curso Online Desarrollo Videojuegos con Unity", description=lorem_ipsum.paragraph(), price=Decimal('75.00'), stock=1000, tags="Software, Educativo, Programación, Videojuegos"),

    # Material de Oficina y Escolar (20 productos)
    Product(name="Pack 10 Bolígrafos Gel Colores Surtidos", description=lorem_ipsum.paragraph(), price=Decimal('12.99'), stock=300, tags="Oficina, Escolar, Escritura, Bolígrafos"),
    Product(name="Cuaderno Tapa Dura A5 Rayado (Pack 3)", description=lorem_ipsum.paragraph(), price=Decimal('18.50'), stock=250, tags="Oficina, Escolar, Papelería, Cuadernos"),
    Product(name="Mochila Escolar Ergonómica Reforzada", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=120, tags="Escolar, Mochila, Infantil, Organización"),
    Product(name="Set Lápices de Colores Profesionales (72 unidades)", description=lorem_ipsum.paragraph(), price=Decimal('35.75'), stock=150, tags="Escolar, Arte, Lápices Colores, Dibujo"),
    Product(name="Agenda Anual 2025 Vista Semanal Piel Sintética", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=180, tags="Oficina, Agenda, Planificación, 2025"),
    Product(name="Grapadora Escritorio Metálica + Grapas", description=lorem_ipsum.paragraph(), price=Decimal('15.90'), stock=200, tags="Oficina, Grapadora, Accesorios, Escritorio"),
    Product(name="Tijeras Multiuso Acero Inoxidable Mango Suave", description=lorem_ipsum.paragraph(), price=Decimal('9.95'), stock=220, tags="Oficina, Escolar, Tijeras, Corte"),
    Product(name="Set Marcadores Permanentes Punta Fina (12 colores)", description=lorem_ipsum.paragraph(), price=Decimal('19.00'), stock=170, tags="Oficina, Escolar, Marcadores, Escritura"),
    Product(name="Carpeta Clasificadora Archivador Anillas", description=lorem_ipsum.paragraph(), price=Decimal('10.50'), stock=280, tags="Oficina, Escolar, Organización, Archivo"),
    Product(name="Calculadora Científica Avanzada Solar/Pila", description=lorem_ipsum.paragraph(), price=Decimal('28.99'), stock=100, tags="Escolar, Oficina, Calculadora, Científica"),
    Product(name="Notas Adhesivas Colores Pastel (Pack 6)", description=lorem_ipsum.paragraph(), price=Decimal('8.00'), stock=400, tags="Oficina, Papelería, Notas Adhesivas, Recordatorios"),
    Product(name="Estuche Escolar Grande Triple Cremallera", description=lorem_ipsum.paragraph(), price=Decimal('16.70'), stock=160, tags="Escolar, Estuche, Organización, Lápices"),
    Product(name="Pizarra Blanca Magnética Pequeña con Rotulador", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=90, tags="Oficina, Escolar, Pizarra, Presentación"),
    Product(name="Papel Fotográfico A4 Brillante (100 hojas)", description=lorem_ipsum.paragraph(), price=Decimal('17.80'), stock=130, tags="Oficina, Impresión, Papel Fotográfico, Calidad"),
    Product(name="Destructora de Papel Manual Pequeña Oficina", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=70, tags="Oficina, Seguridad, Destructora, Documentos"),
    Product(name="Cinta Adhesiva Transparente (Pack 3 Rollos)", description=lorem_ipsum.paragraph(), price=Decimal('6.50'), stock=350, tags="Oficina, Escolar, Cinta Adhesiva, Embalaje"),
    Product(name="Rotuladores Pizarra Blanca Recargables (4 colores)", description=lorem_ipsum.paragraph(), price=Decimal('14.99'), stock=190, tags="Oficina, Escolar, Pizarra, Rotuladores"),
    Product(name="Organizador de Escritorio Malla Metálica", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=110, tags="Oficina, Organización, Escritorio, Accesorios"),
    Product(name="Corrector Cinta Tippex Secado Rápido (Pack 2)", description=lorem_ipsum.paragraph(), price=Decimal('7.25'), stock=260, tags="Oficina, Escolar, Corrector, Escritura"),
    Product(name="Plastificadora A4 Oficina Doméstica + Fundas", description=lorem_ipsum.paragraph(), price=Decimal('42.90'), stock=80, tags="Oficina, Plastificadora, Documentos, Protección"),

    # Arte y Manualidades (20 productos)
    Product(name="Set Pinturas Acrílicas Tubos 24 Colores", description=lorem_ipsum.paragraph(), price=Decimal('28.99'), stock=120, tags="Arte, Manualidades, Pintura, Acrílico"),
    Product(name="Lienzo de Algodón Preestirado (Pack 3, 30x40cm)", description=lorem_ipsum.paragraph(), price=Decimal('22.50'), stock=150, tags="Arte, Pintura, Lienzo, Algodón"),
    Product(name="Set Pinceles Artista Varias Formas y Tamaños", description=lorem_ipsum.paragraph(), price=Decimal('19.00'), stock=180, tags="Arte, Pintura, Pinceles, Accesorios"),
    Product(name="Arcilla Polimérica Kit Modelado Horno (36 colores)", description=lorem_ipsum.paragraph(), price=Decimal('33.75'), stock=100, tags="Manualidades, Modelado, Arcilla Polimérica, Creativo"),
    Product(name="Papel Acuarela Grano Fino A4 (30 hojas)", description=lorem_ipsum.paragraph(), price=Decimal('15.00'), stock=200, tags="Arte, Pintura, Acuarela, Papel"),
    Product(name="Kit Bordado Principiantes Hilos y Agujas", description=lorem_ipsum.paragraph(), price=Decimal('25.90'), stock=90, tags="Manualidades, Bordado, Textil, Kit"),
    Product(name="Pistola de Silicona Caliente con Barras", description=lorem_ipsum.paragraph(), price=Decimal('18.95'), stock=130, tags="Manualidades, Herramientas, Silicona Caliente, Pegamento"),
    Product(name="Caballete de Mesa Madera Haya Plegable", description=lorem_ipsum.paragraph(), price=Decimal('40.00'), stock=70, tags="Arte, Pintura, Caballete, Soporte"),
    Product(name="Set Rotuladores Caligrafía Punta Pincel", description=lorem_ipsum.paragraph(), price=Decimal('29.00'), stock=110, tags="Arte, Caligrafía, Rotuladores, Lettering"),
    Product(name="Goma Eva Planchas Colores Surtidos (Pack 20)", description=lorem_ipsum.paragraph(), price=Decimal('12.99'), stock=250, tags="Manualidades, Goma Eva, Infantil, Creativo"),
    Product(name="Lana para Tejer Ovillos Acrílicos (Pack 10)", description=lorem_ipsum.paragraph(), price=Decimal('30.50'), stock=0, tags="Manualidades, Tejer, Lana, Textil"), # Stock 0
    Product(name="Troqueladoras Formas Variadas Scrapbooking", description=lorem_ipsum.paragraph(), price=Decimal('24.80'), stock=80, tags="Manualidades, Scrapbooking, Troqueladoras, Papel"),
    Product(name="Cuentas y Abalorios para Bisutería (Caja Surtida)", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=160, tags="Manualidades, Bisutería, Cuentas, Joyería DIY"),
    Product(name="Tabla de Corte Autocicatrizante A3 Patchwork", description=lorem_ipsum.paragraph(), price=Decimal('27.00'), stock=95, tags="Manualidades, Costura, Patchwork, Herramientas"),
    Product(name="Kit Velas DIY Cera Soja y Aromas", description=lorem_ipsum.paragraph(), price=Decimal('38.90'), stock=60, tags="Manualidades, Velas, DIY, Aromaterapia"),
    Product(name="Sellos de Goma Alfabeto y Números para Estampar", description=lorem_ipsum.paragraph(), price=Decimal('21.70'), stock=100, tags="Manualidades, Estampación, Sellos, Scrapbooking"),
    Product(name="Fieltro de Colores Láminas para Manualidades", description=lorem_ipsum.paragraph(), price=Decimal('14.00'), stock=140, tags="Manualidades, Fieltro, Textil, Infantil"),
    Product(name="Aerógrafo Kit Básico con Compresor Pequeño", description=lorem_ipsum.paragraph(), price=Decimal('95.99'), stock=40, tags="Arte, Pintura, Aerografía, Modelismo"),
    Product(name="Washi Tape Decorativo Diseños Variados (Pack 12)", description=lorem_ipsum.paragraph(), price=Decimal('16.50'), stock=170, tags="Manualidades, Scrapbooking, Washi Tape, Decoración"),
    Product(name="Libro Colorear Adultos Mandalas Anti- estrés", description=lorem_ipsum.paragraph(), price=Decimal('10.95'), stock=220, tags="Arte, Colorear, Adultos, Anti-estrés"),

    # Salud y Cuidado Personal (20 productos)
    Product(name="Cepillo Dental Eléctrico Sónico Recargable", description=lorem_ipsum.paragraph(), price=Decimal('59.99'), stock=90, tags="Salud, Cuidado Bucal, Cepillo Eléctrico, Higiene"),
    Product(name="Termómetro Digital Infrarrojo Sin Contacto", description=lorem_ipsum.paragraph(), price=Decimal('28.50'), stock=120, tags="Salud, Medición, Termómetro, Bebés"),
    Product(name="Tensiómetro de Brazo Digital Automático", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=70, tags="Salud, Medición, Tensión Arterial, Monitor"),
    Product(name="Crema Hidratante Facial Ácido Hialurónico", description=lorem_ipsum.paragraph(), price=Decimal('22.75'), stock=150, tags="Cuidado Personal, Piel, Hidratación, Antiedad"),
    Product(name="Champú Anticaída Fortalecedor Biotina", description=lorem_ipsum.paragraph(), price=Decimal('18.00'), stock=180, tags="Cuidado Personal, Cabello, Anticaída, Champú"),
    Product(name="Protector Solar SPF 50+ Facial Piel Sensible", description=lorem_ipsum.paragraph(), price=Decimal('20.90'), stock=200, tags="Cuidado Personal, Piel, Protección Solar, Verano"),
    Product(name="Set Manicura y Pedicura Profesional Acero Inox", description=lorem_ipsum.paragraph(), price=Decimal('33.00'), stock=100, tags="Cuidado Personal, Uñas, Manicura, Pedicura"),
    Product(name="Aceite Esencial Lavanda Puro Aromaterapia", description=lorem_ipsum.paragraph(), price=Decimal('15.95'), stock=160, tags="Salud, Bienestar, Aromaterapia, Aceites Esenciales"),
    Product(name="Masajeador Cervical Shiatsu Calor", description=lorem_ipsum.paragraph(), price=Decimal('65.00'), stock=60, tags="Salud, Bienestar, Masaje, Relax"),
    Product(name="Suplemento Vitamina C 1000mg (100 Comprimidos)", description=lorem_ipsum.paragraph(), price=Decimal('12.99'), stock=250, tags="Salud, Suplementos, Vitaminas, Inmunidad"),
    Product(name="Irrigador Bucal Portátil Recargable", description=lorem_ipsum.paragraph(), price=Decimal('48.80'), stock=80, tags="Salud, Cuidado Bucal, Irrigador, Higiene"),
    Product(name="Almohada Ortopédica Cervical Viscoelástica", description=lorem_ipsum.paragraph(), price=Decimal('39.00'), stock=110, tags="Salud, Descanso, Almohada, Ortopédico"),
    Product(name="Bálsamo Labial Reparador Manteca Karité", description=lorem_ipsum.paragraph(), price=Decimal('8.50'), stock=300, tags="Cuidado Personal, Labios, Hidratación, Bálsamo"),
    Product(name="Desodorante Natural Sin Aluminio Roll-on", description=lorem_ipsum.paragraph(), price=Decimal('10.70'), stock=140, tags="Cuidado Personal, Higiene, Desodorante, Natural"),
    Product(name="Parches Antifatiga Contorno Ojos Colágeno", description=lorem_ipsum.paragraph(), price=Decimal('16.00'), stock=130, tags="Cuidado Personal, Piel, Ojos, Antifatiga"),
    Product(name="Humidificador Ultrasónico Aromadifusor LED", description=lorem_ipsum.paragraph(), price=Decimal('35.99'), stock=95, tags="Salud, Bienestar, Humidificador, Aromaterapia"),
    Product(name="Jabón Artesanal Glicerina y Aceites Naturales (Pack 3)", description=lorem_ipsum.paragraph(), price=Decimal('14.00'), stock=170, tags="Cuidado Personal, Higiene, Jabón, Natural"),
    Product(name="Lima Eléctrica Durezas Pies Profesional", description=lorem_ipsum.paragraph(), price=Decimal('29.90'), stock=85, tags="Cuidado Personal, Pies, Pedicura, Durezas"),
    Product(name="Suplemento Omega 3 Aceite Pescado (120 Cápsulas)", description=lorem_ipsum.paragraph(), price=Decimal('19.95'), stock=190, tags="Salud, Suplementos, Omega 3, Bienestar"),
    Product(name="Kit Depilación Cera Caliente Profesional Casa", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=50, tags="Cuidado Personal, Depilación, Cera, Belleza"),

    # Belleza y Cosméticos (20 productos)
    Product(name="Paleta Sombras Ojos Nude 12 Colores", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=150, tags="Belleza, Maquillaje, Ojos, Sombras"),
    Product(name="Base Maquillaje Fluida Cobertura Total Larga Duración", description=lorem_ipsum.paragraph(), price=Decimal('32.50'), stock=120, tags="Belleza, Maquillaje, Rostro, Base"),
    Product(name="Máscara de Pestañas Volumen Extremo Waterproof", description=lorem_ipsum.paragraph(), price=Decimal('18.00'), stock=200, tags="Belleza, Maquillaje, Ojos, Máscara Pestañas"),
    Product(name="Labial Mate Fijo Color Intenso (Varios Tonos)", description=lorem_ipsum.paragraph(), price=Decimal('15.75'), stock=250, tags="Belleza, Maquillaje, Labios, Labial Mate"),
    Product(name="Set Brochas Maquillaje Profesional (10 piezas) Pelo Sintético", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=100, tags="Belleza, Maquillaje, Accesorios, Brochas"),
    Product(name="Perfume Eau de Parfum Floral Mujer 50ml", description=lorem_ipsum.paragraph(), price=Decimal('65.90'), stock=80, tags="Belleza, Perfumes, Mujer, Floral"),
    Product(name="Delineador Ojos Líquido Negro Intenso Precisión", description=lorem_ipsum.paragraph(), price=Decimal('12.00'), stock=180, tags="Belleza, Maquillaje, Ojos, Delineador"),
    Product(name="Corrector Ojeras Iluminador Alta Cobertura", description=lorem_ipsum.paragraph(), price=Decimal('19.90'), stock=160, tags="Belleza, Maquillaje, Rostro, Corrector"),
    Product(name="Polvos Translúcidos Matificantes Fijadores", description=lorem_ipsum.paragraph(), price=Decimal('22.50'), stock=130, tags="Belleza, Maquillaje, Rostro, Polvos"),
    Product(name="Esponja Maquillaje Blender Sin Látex", description=lorem_ipsum.paragraph(), price=Decimal('9.99'), stock=300, tags="Belleza, Maquillaje, Accesorios, Esponja"),
    Product(name="Agua Micelar Limpiadora Desmaquillante Piel Sensible", description=lorem_ipsum.paragraph(), price=Decimal('14.50'), stock=170, tags="Belleza, Cuidado Piel, Limpieza, Desmaquillante"),
    Product(name="Crema BB Cream Hidratante con Color SPF 30", description=lorem_ipsum.paragraph(), price=Decimal('27.00'), stock=110, tags="Belleza, Maquillaje, Rostro, BB Cream"),
    Product(name="Sérum Facial Vitamina C Antioxidante Iluminador", description=lorem_ipsum.paragraph(), price=Decimal('35.80'), stock=90, tags="Belleza, Cuidado Piel, Sérum, Vitamina C"),
    Product(name="Lápiz de Cejas Relleno y Definición con Cepillo", description=lorem_ipsum.paragraph(), price=Decimal('11.00'), stock=190, tags="Belleza, Maquillaje, Cejas, Lápiz"),
    Product(name="Colorete en Polvo Melocotón Satinado", description=lorem_ipsum.paragraph(), price=Decimal('16.70'), stock=140, tags="Belleza, Maquillaje, Rostro, Colorete"),
    Product(name="Tratamiento Fortalecedor Uñas Queratina", description=lorem_ipsum.paragraph(), price=Decimal('13.00'), stock=0, tags="Belleza, Cuidado Uñas, Tratamiento, Fortalecedor"), # Stock 0
    Product(name="Neceser Maquillaje Viaje Organizador", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=85, tags="Belleza, Accesorios, Neceser, Viaje"),
    Product(name="Fijador Maquillaje Spray Larga Duración", description=lorem_ipsum.paragraph(), price=Decimal('20.95'), stock=95, tags="Belleza, Maquillaje, Fijador, Spray"),
    Product(name="Rizador de Pestañas Acero Inoxidable", description=lorem_ipsum.paragraph(), price=Decimal('10.00'), stock=220, tags="Belleza, Maquillaje, Accesorios, Rizador Pestañas"),
    Product(name="Mascarilla Facial Purificante Arcilla Verde", description=lorem_ipsum.paragraph(), price=Decimal('17.99'), stock=100, tags="Belleza, Cuidado Piel, Mascarilla, Purificante"),

    # Bebés y Maternidad (20 productos)
    Product(name="Pañales Desechables Bebé Talla 3 (Pack 100)", description=lorem_ipsum.paragraph(), price=Decimal('35.99'), stock=200, tags="Bebés, Pañales, Higiene, Desechables"),
    Product(name="Carrito Bebé Plegable Ligero 3 en 1 (Silla, Capazo, Grupo 0)", description=lorem_ipsum.paragraph(), price=Decimal('350.50'), stock=30, tags="Bebés, Carritos, Paseo, Viaje"),
    Product(name="Cuna Convertible Madera Blanca con Colchón", description=lorem_ipsum.paragraph(), price=Decimal('280.00'), stock=25, tags="Bebés, Mobiliario, Cuna, Dormitorio"),
    Product(name="Silla de Coche Bebé Grupo 0+/1/2/3 Isofix Rotatoria", description=lorem_ipsum.paragraph(), price=Decimal('220.75'), stock=40, tags="Bebés, Seguridad Vial, Silla Coche, Isofix"),
    Product(name="Vigilabebés con Cámara y Visión Nocturna", description=lorem_ipsum.paragraph(), price=Decimal('99.00'), stock=60, tags="Bebés, Seguridad, Vigilabebés, Monitor"),
    Product(name="Biberones Anticólicos Set Recién Nacido", description=lorem_ipsum.paragraph(), price=Decimal('45.90'), stock=100, tags="Bebés, Alimentación, Biberones, Anticólicos"),
    Product(name="Extractor de Leche Eléctrico Doble Portátil", description=lorem_ipsum.paragraph(), price=Decimal('130.00'), stock=50, tags="Maternidad, Lactancia, Extractor Leche, Eléctrico"),
    Product(name="Hamaca Bebé Vibratoria y Musical", description=lorem_ipsum.paragraph(), price=Decimal('75.00'), stock=70, tags="Bebés, Descanso, Hamaca, Entretenimiento"),
    Product(name="Mochila Portabebés Ergonómica Multiposición", description=lorem_ipsum.paragraph(), price=Decimal('88.95'), stock=80, tags="Bebés, Porteo, Mochila, Ergonómica"),
    Product(name="Termómetro Baño Bebé Forma Animalito", description=lorem_ipsum.paragraph(), price=Decimal('12.50'), stock=150, tags="Bebés, Higiene, Baño, Termómetro"),
    Product(name="Cojín Lactancia Ergonómico Desenfundable", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=90, tags="Maternidad, Lactancia, Cojín, Confort"),
    Product(name="Parque Bebé Plegable Área de Juegos Segura", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=35, tags="Bebés, Seguridad, Parque, Juegos"),
    Product(name="Juguete Mordedor Silicona Bebé Alivio Dentición", description=lorem_ipsum.paragraph(), price=Decimal('10.99'), stock=200, tags="Bebés, Juguetes, Mordedor, Dentición"),
    Product(name="Toallitas Húmedas Bebé Piel Sensible (Pack 12x60)", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=180, tags="Bebés, Higiene, Toallitas, Piel Sensible"),
    Product(name="Crema Pañal Bebé Óxido Zinc Protectora", description=lorem_ipsum.paragraph(), price=Decimal('9.70'), stock=220, tags="Bebés, Higiene, Crema Pañal, Protección"),
    Product(name="Bañera Bebé Plegable con Soporte Antideslizante", description=lorem_ipsum.paragraph(), price=Decimal('55.90'), stock=65, tags="Bebés, Higiene, Bañera, Plegable"),
    Product(name="Calienta Biberones Rápido y Esterilizador", description=lorem_ipsum.paragraph(), price=Decimal('49.00'), stock=75, tags="Bebés, Alimentación, Calienta Biberones, Esterilizador"),
    Product(name="Body Bebé Algodón Orgánico Manga Larga (Pack 5)", description=lorem_ipsum.paragraph(), price=Decimal('30.00'), stock=160, tags="Bebés, Ropa, Body, Algodón Orgánico"),
    Product(name="Saco de Dormir Bebé Invierno Algodón Acolchado", description=lorem_ipsum.paragraph(), price=Decimal('42.99'), stock=0, tags="Bebés, Descanso, Saco Dormir, Invierno"), # Stock 0
    Product(name="Luz Nocturna Infantil LED Proyector Estrellas", description=lorem_ipsum.paragraph(), price=Decimal('25.00'), stock=110, tags="Bebés, Dormitorio, Luz Nocturna, Proyector"),

    # Mascotas (20 productos)
    Product(name="Pienso Perro Adulto Razas Medianas Salmón (12kg)", description=lorem_ipsum.paragraph(), price=Decimal('45.99'), stock=100, tags="Mascotas, Perros, Alimentación, Pienso"),
    Product(name="Arena Aglomerante Gato Ultra Absorbente Lavanda (10L)", description=lorem_ipsum.paragraph(), price=Decimal('18.50'), stock=150, tags="Mascotas, Gatos, Higiene, Arena"),
    Product(name="Cama Perro Mediana Ortopédica Viscoelástica", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=70, tags="Mascotas, Perros, Descanso, Cama Ortopédica"),
    Product(name="Rascador Gato Torre Multinivel con Hamaca", description=lorem_ipsum.paragraph(), price=Decimal('70.75'), stock=50, tags="Mascotas, Gatos, Juguetes, Rascador"),
    Product(name="Correa Perro Extensible Reflectante 5m", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=120, tags="Mascotas, Perros, Paseo, Correa"),
    Product(name="Juguete Interactivo Perro Dispensador Premios", description=lorem_ipsum.paragraph(), price=Decimal('15.90'), stock=180, tags="Mascotas, Perros, Juguetes, Interactivo"),
    Product(name="Transportín Gato/Perro Pequeño Homologado Avión", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=80, tags="Mascotas, Viaje, Transportín, Seguridad"),
    Product(name="Comedero y Bebedero Acero Inoxidable Antideslizante (Set 2)", description=lorem_ipsum.paragraph(), price=Decimal('19.95'), stock=200, tags="Mascotas, Alimentación, Comedero, Acero"),
    Product(name="Champú Perro Piel Sensible Aloe Vera", description=lorem_ipsum.paragraph(), price=Decimal('12.00'), stock=160, tags="Mascotas, Perros, Higiene, Champú"),
    Product(name="Snacks Dentales Perro Anti Sarro (Pack Grande)", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=130, tags="Mascotas, Perros, Premios, Cuidado Dental"),
    Product(name="Fuente Agua Gato Automática Silenciosa Filtro", description=lorem_ipsum.paragraph(), price=Decimal('33.50'), stock=90, tags="Mascotas, Gatos, Hidratación, Fuente"),
    Product(name="Collar Antiparasitario Perro Larga Duración", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=110, tags="Mascotas, Perros, Salud, Antiparasitario"),
    Product(name="Juguete Varita Plumas Gato Interactivo", description=lorem_ipsum.paragraph(), price=Decimal('9.90'), stock=250, tags="Mascotas, Gatos, Juguetes, Varita"),
    Product(name="Abrigo Perro Invierno Impermeable Forro Polar", description=lorem_ipsum.paragraph(), price=Decimal('30.70'), stock=60, tags="Mascotas, Perros, Ropa, Invierno"),
    Product(name="Bolsas Caca Perro Biodegradables con Dispensador", description=lorem_ipsum.paragraph(), price=Decimal('14.00'), stock=300, tags="Mascotas, Perros, Higiene, Bolsas"),
    Product(name="Jaula Hámster Grande Accesorios Incluidos", description=lorem_ipsum.paragraph(), price=Decimal('48.00'), stock=40, tags="Mascotas, Roedores, Hábitat, Jaula"),
    Product(name="Alimento Húmedo Gato Paté Salmón (Pack 24 Latas)", description=lorem_ipsum.paragraph(), price=Decimal('29.95'), stock=100, tags="Mascotas, Gatos, Alimentación, Comida Húmeda"),
    Product(name="Cepillo Quita Pelo Muerto Perro/Gato Doble Cara", description=lorem_ipsum.paragraph(), price=Decimal('16.99'), stock=140, tags="Mascotas, Higiene, Cepillo, Peluquería"),
    Product(name="Acuario Cristal Kit Completo Principiantes 20L", description=lorem_ipsum.paragraph(), price=Decimal('65.00'), stock=30, tags="Mascotas, Peces, Acuario, Kit"),
    Product(name="Empapadores Adiestramiento Cachorros Ultra Absorbentes", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=170, tags="Mascotas, Perros, Adiestramiento, Empapadores"),

    # Herramientas y Mejoras del Hogar (20 productos)
    Product(name="Taladro Percutor Inalámbrico 18V con 2 Baterías", description=lorem_ipsum.paragraph(), price=Decimal('120.99'), stock=60, tags="Herramientas, Eléctricas, Taladro, Bricolaje"),
    Product(name="Caja Herramientas Completa 128 Piezas Cromo Vanadio", description=lorem_ipsum.paragraph(), price=Decimal('99.50'), stock=40, tags="Herramientas, Manuales, Set, Profesional"),
    Product(name="Sierra Circular Eléctrica 1500W Guía Láser", description=lorem_ipsum.paragraph(), price=Decimal('85.00'), stock=30, tags="Herramientas, Eléctricas, Sierra, Corte Madera"),
    Product(name="Set Destornilladores Precisión Electrónica (32 piezas)", description=lorem_ipsum.paragraph(), price=Decimal('18.75'), stock=150, tags="Herramientas, Manuales, Destornilladores, Electrónica"),
    Product(name="Escalera Telescópica Aluminio Plegable 3.8m", description=lorem_ipsum.paragraph(), price=Decimal('110.00'), stock=25, tags="Mejoras Hogar, Escalera, Seguridad, Aluminio"),
    Product(name="Nivel Láser Autonivelante Cruz Verde", description=lorem_ipsum.paragraph(), price=Decimal('65.90'), stock=50, tags="Herramientas, Medición, Nivel Láser, Precisión"),
    Product(name="Pistola de Pintar Eléctrica Pulverizadora HVLP", description=lorem_ipsum.paragraph(), price=Decimal('70.00'), stock=35, tags="Mejoras Hogar, Pintura, Pistola, Eléctrica"),
    Product(name="Llave Inglesa Ajustable Universal Grande", description=lorem_ipsum.paragraph(), price=Decimal('22.99'), stock=100, tags="Herramientas, Manuales, Llave Inglesa, Fontanería"),
    Product(name="Amoladora Angular (Radial) 750W Disco 115mm", description=lorem_ipsum.paragraph(), price=Decimal('55.00'), stock=45, tags="Herramientas, Eléctricas, Amoladora, Corte Metal"),
    Product(name="Cinta Métrica Profesional Autoblocante 5m", description=lorem_ipsum.paragraph(), price=Decimal('12.50'), stock=200, tags="Herramientas, Medición, Cinta Métrica, Precisión"),
    Product(name="Kit Soldador Estaño Eléctrico Temperatura Regulable", description=lorem_ipsum.paragraph(), price=Decimal('30.95'), stock=80, tags="Herramientas, Soldadura, Electrónica, Estaño"),
    Product(name="Guantes de Trabajo Seguridad Anticorte Nivel 5", description=lorem_ipsum.paragraph(), price=Decimal('19.00'), stock=120, tags="Herramientas, Protección, Guantes, Seguridad"),
    Product(name="Detector de Metales y Tensión Pared Digital", description=lorem_ipsum.paragraph(), price=Decimal('42.80'), stock=60, tags="Mejoras Hogar, Detección, Seguridad, Electricidad"),
    Product(name="Multiherramienta Oscilante Inalámbrica Accesorios", description=lorem_ipsum.paragraph(), price=Decimal('95.00'), stock=0, tags="Herramientas, Eléctricas, Multiherramienta, Versátil"), # Stock 0
    Product(name="Tornillo de Banco sobremesa Giratorio", description=lorem_ipsum.paragraph(), price=Decimal('48.00'), stock=30, tags="Herramientas, Taller, Tornillo Banco, Sujeción"),
    Product(name="Martillo Carpintero Mango Fibra Vidrio Antivibración", description=lorem_ipsum.paragraph(), price=Decimal('16.70'), stock=130, tags="Herramientas, Manuales, Martillo, Carpintería"),
    Product(name="Juego Llaves Allen Hexagonales Punta Bola (9 piezas)", description=lorem_ipsum.paragraph(), price=Decimal('14.99'), stock=180, tags="Herramientas, Manuales, Llaves Allen, Mecánica"),
    Product(name="Linterna LED Trabajo Recargable Imantada Gancho", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=90, tags="Herramientas, Iluminación, Linterna, Trabajo"),
    Product(name="Decapadora Pistola Aire Caliente Profesional 2000W", description=lorem_ipsum.paragraph(), price=Decimal('39.90'), stock=55, tags="Herramientas, Eléctricas, Decapadora, Pintura"),
    Product(name="Gafas de Seguridad Protección Policarbonato Antivaho", description=lorem_ipsum.paragraph(), price=Decimal('10.00'), stock=250, tags="Herramientas, Protección, Gafas, Seguridad"),

    # Automotriz (20 productos)
    Product(name="Arrancador de Coche Batería Portátil 1200A Powerbank", description=lorem_ipsum.paragraph(), price=Decimal('89.99'), stock=70, tags="Automotriz, Batería, Emergencia, Arrancador"),
    Product(name="Aspiradora de Mano para Coche Potente 12V", description=lorem_ipsum.paragraph(), price=Decimal('35.50'), stock=120, tags="Automotriz, Limpieza, Aspiradora, Interior"),
    Product(name="Funda Exterior Coche Impermeable Transpirable Talla L", description=lorem_ipsum.paragraph(), price=Decimal('45.00'), stock=50, tags="Automotriz, Protección, Funda, Exterior"),
    Product(name="Kit Limpieza Coche Completo (Cera, Champú, Microfibras)", description=lorem_ipsum.paragraph(), price=Decimal('55.75'), stock=80, tags="Automotriz, Limpieza, Cuidado, Kit"),
    Product(name="Compresor Aire Portátil Digital 12V Neumáticos", description=lorem_ipsum.paragraph(), price=Decimal('42.00'), stock=100, tags="Automotriz, Neumáticos, Emergencia, Compresor"),
    Product(name="Soporte Móvil Coche Magnético Salpicadero/Rejilla", description=lorem_ipsum.paragraph(), price=Decimal('18.90'), stock=200, tags="Automotriz, Accesorios, Soporte Móvil, Seguridad"),
    Product(name="Cargador USB Coche Carga Rápida Múltiples Puertos", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=150, tags="Automotriz, Accesorios, Cargador USB, Electrónica"),
    Product(name="Alfombrillas Coche Goma Universales Recortables", description=lorem_ipsum.paragraph(), price=Decimal('30.99'), stock=90, tags="Automotriz, Interior, Alfombrillas, Protección"),
    Product(name="Lámparas LED H7 Coche Luz Blanca Potente (Par)", description=lorem_ipsum.paragraph(), price=Decimal('38.00'), stock=110, tags="Automotriz, Iluminación, LED, Faros"),
    Product(name="Organizador Maletero Coche Plegable Múltiples Compartimentos", description=lorem_ipsum.paragraph(), price=Decimal('25.50'), stock=130, tags="Automotriz, Organización, Maletero, Accesorios"),
    Product(name="Cadenas Nieve Textiles Coche Talla M", description=lorem_ipsum.paragraph(), price=Decimal('60.00'), stock=60, tags="Automotriz, Seguridad, Invierno, Cadenas Nieve"),
    Product(name="Rasqueta Hielo Coche con Guante Forrado", description=lorem_ipsum.paragraph(), price=Decimal('12.95'), stock=180, tags="Automotriz, Invierno, Accesorios, Hielo"),
    Product(name="Aditivo Limpia Inyectores Diésel/Gasolina", description=lorem_ipsum.paragraph(), price=Decimal('15.70'), stock=160, tags="Automotriz, Mantenimiento, Aditivo, Motor"),
    Product(name="Parasol Delantero Coche Plegable Protección UV", description=lorem_ipsum.paragraph(), price=Decimal('10.00'), stock=250, tags="Automotriz, Accesorios, Parasol, Protección Solar"),
    Product(name="Cámara Trasera Aparcamiento Coche Visión Nocturna", description=lorem_ipsum.paragraph(), price=Decimal('49.90'), stock=70, tags="Automotriz, Seguridad, Aparcamiento, Cámara"),
    Product(name="Kit Reparación Pinchazos Neumáticos sin Cámara", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=95, tags="Automotriz, Emergencia, Neumáticos, Reparación"),
    Product(name="Ambientador Coche Colgante Larga Duración (Pack 3)", description=lorem_ipsum.paragraph(), price=Decimal('9.99'), stock=300, tags="Automotriz, Accesorios, Ambientador, Interior"),
    Product(name="Gato Hidráulico Botella Coche 2 Toneladas", description=lorem_ipsum.paragraph(), price=Decimal('33.80'), stock=55, tags="Automotriz, Herramientas, Emergencia, Gato"),
    Product(name="Líquido Limpiaparabrisas Concentrado Antilluvia", description=lorem_ipsum.paragraph(), price=Decimal('8.50'), stock=220, tags="Automotriz, Mantenimiento, Limpiaparabrisas, Visibilidad"),
    Product(name="Manómetro Presión Neumáticos Digital Precisión", description=lorem_ipsum.paragraph(), price=Decimal('17.00'), stock=140, tags="Automotriz, Neumáticos, Medición, Seguridad"),

    # Alimentos Gourmet y Bebidas (No Perecederos - 20 productos)
    Product(name="Café en Grano Arábica Tostado Natural (1kg)", description=lorem_ipsum.paragraph(), price=Decimal('25.99'), stock=150, tags="Alimentos, Gourmet, Café, Bebidas"),
    Product(name="Aceite Oliva Virgen Extra Ecológico Botella Vidrio 500ml", description=lorem_ipsum.paragraph(), price=Decimal('18.50'), stock=120, tags="Alimentos, Gourmet, Aceite Oliva, Ecológico"),
    Product(name="Selección Tés del Mundo Caja Regalo (24 Bolsitas)", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=100, tags="Alimentos, Gourmet, Té, Bebidas"),
    Product(name="Chocolate Negro Artesanal 85% Cacao Tableta", description=lorem_ipsum.paragraph(), price=Decimal('8.75'), stock=200, tags="Alimentos, Gourmet, Chocolate, Dulces"),
    Product(name="Miel Cruda Milflores Tarro Cristal 500g", description=lorem_ipsum.paragraph(), price=Decimal('15.00'), stock=130, tags="Alimentos, Gourmet, Miel, Natural"),
    Product(name="Vinagre Balsámico de Módena Envejecido IGP", description=lorem_ipsum.paragraph(), price=Decimal('19.90'), stock=80, tags="Alimentos, Gourmet, Vinagre Balsámico, Condimentos"),
    Product(name="Conservas Pescado Gourmet Ventresca Atún Aceite Oliva", description=lorem_ipsum.paragraph(), price=Decimal('12.50'), stock=160, tags="Alimentos, Gourmet, Conservas, Pescado"),
    Product(name="Pasta Artesanal Italiana Trigo Duro (500g)", description=lorem_ipsum.paragraph(), price=Decimal('7.95'), stock=180, tags="Alimentos, Gourmet, Pasta, Italiana"),
    Product(name="Arroz Bomba Paella D.O. Valencia (1kg)", description=lorem_ipsum.paragraph(), price=Decimal('10.00'), stock=110, tags="Alimentos, Gourmet, Arroz, Paella"),
    Product(name="Paté de Pato Foie Gras Lata", description=lorem_ipsum.paragraph(), price=Decimal('28.99'), stock=70, tags="Alimentos, Gourmet, Paté, Foie Gras"),
    Product(name="Mermelada Artesanal Frutos Rojos Sin Azúcar Añadido", description=lorem_ipsum.paragraph(), price=Decimal('9.50'), stock=140, tags="Alimentos, Gourmet, Mermelada, Sin Azúcar"),
    Product(name="Set Sales del Mundo para Cocina (Flor de Sal, Himalaya, Persia)", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=90, tags="Alimentos, Gourmet, Especias, Sales"),
    Product(name="Galletas Artesanas Mantequilla Caja Metálica", description=lorem_ipsum.paragraph(), price=Decimal('16.70'), stock=100, tags="Alimentos, Gourmet, Galletas, Dulces"),
    Product(name="Vino Tinto Reserva D.O. Rioja Botella", description=lorem_ipsum.paragraph(), price=Decimal('18.80'), stock=0, tags="Bebidas, Gourmet, Vino, Tinto"), # Stock 0
    Product(name="Cerveza Artesana IPA Pack Degustación (6 Botellas)", description=lorem_ipsum.paragraph(), price=Decimal('29.00'), stock=60, tags="Bebidas, Gourmet, Cerveza, Artesana"),
    Product(name="Frutos Secos Tostados Premium Mezcla (Almendras, Nueces, Avellanas)", description=lorem_ipsum.paragraph(), price=Decimal('14.99'), stock=170, tags="Alimentos, Gourmet, Frutos Secos, Snacks"),
    Product(name="Salsa Pesto Genovés Artesanal", description=lorem_ipsum.paragraph(), price=Decimal('11.00'), stock=95, tags="Alimentos, Gourmet, Salsas, Pesto"),
    Product(name="Turrón Artesano Jijona Calidad Suprema Barra", description=lorem_ipsum.paragraph(), price=Decimal('13.00'), stock=50, tags="Alimentos, Gourmet, Dulces, Turrón"),
    Product(name="Mostaza Antigua Dijon Tarro Cerámica", description=lorem_ipsum.paragraph(), price=Decimal('10.95'), stock=85, tags="Alimentos, Gourmet, Condimentos, Mostaza"),
    Product(name="Infusión Digestiva Ecológica (Manzanilla, Anís, Hinojo)", description=lorem_ipsum.paragraph(), price=Decimal('7.50'), stock=190, tags="Alimentos, Gourmet, Infusión, Ecológica"),

    # Viajes (20 productos)
    Product(name="Maleta Cabina Rígida ABS Ruedas Giratorias 360º", description=lorem_ipsum.paragraph(), price=Decimal('79.99'), stock=90, tags="Viajes, Equipaje, Maleta, Cabina"),
    Product(name="Set 3 Maletas Viaje Rígidas (Cabina, Mediana, Grande)", description=lorem_ipsum.paragraph(), price=Decimal('199.00'), stock=40, tags="Viajes, Equipaje, Set Maletas, Rígidas"),
    Product(name="Mochila de Viaje Antirrobo Impermeable Puerto USB", description=lorem_ipsum.paragraph(), price=Decimal('55.50'), stock=120, tags="Viajes, Mochila, Antirrobo, Tecnología"),
    Product(name="Almohada de Viaje Viscoelástica Cervical con Funda", description=lorem_ipsum.paragraph(), price=Decimal('22.00'), stock=180, tags="Viajes, Accesorios, Confort, Almohada"),
    Product(name="Organizador de Maleta Cubos de Embalaje (Set 7 piezas)", description=lorem_ipsum.paragraph(), price=Decimal('25.75'), stock=150, tags="Viajes, Accesorios, Organización, Maleta"),
    Product(name="Candado TSA Seguridad Combinación para Maletas (Pack 2)", description=lorem_ipsum.paragraph(), price=Decimal('18.00'), stock=200, tags="Viajes, Seguridad, Candado TSA, Maleta"),
    Product(name="Adaptador Enchufe Universal Viaje Internacional", description=lorem_ipsum.paragraph(), price=Decimal('15.90'), stock=250, tags="Viajes, Accesorios, Adaptador, Internacional"),
    Product(name="Báscula Digital Portátil para Equipaje Maletas", description=lorem_ipsum.paragraph(), price=Decimal('12.99'), stock=160, tags="Viajes, Accesorios, Báscula, Equipaje"),
    Product(name="Neceser de Viaje Colgante Impermeable Organizador", description=lorem_ipsum.paragraph(), price=Decimal('20.50'), stock=130, tags="Viajes, Accesorios, Neceser, Organización"),
    Product(name="Botellas de Viaje Silicona Rellenables (Set 4, Anti-fugas)", description=lorem_ipsum.paragraph(), price=Decimal('14.00'), stock=190, tags="Viajes, Accesorios, Contenedores, Líquidos"),
    Product(name="Cartera de Viaje Portadocumentos RFID Bloqueo Pasaporte", description=lorem_ipsum.paragraph(), price=Decimal('28.00'), stock=100, tags="Viajes, Seguridad, Cartera, Documentos"),
    Product(name="Cinturón Dinero Oculto Viaje Antirrobo", description=lorem_ipsum.paragraph(), price=Decimal('19.95'), stock=110, tags="Viajes, Seguridad, Dinero, Antirrobo"),
    Product(name="Antifaz para Dormir Viaje Seda Natural Opaco", description=lorem_ipsum.paragraph(), price=Decimal('10.70'), stock=220, tags="Viajes, Confort, Antifaz, Dormir"),
    Product(name="Toalla Microfibra Secado Rápido Viaje Deporte", description=lorem_ipsum.paragraph(), price=Decimal('16.90'), stock=170, tags="Viajes, Accesorios, Toalla, Microfibra"),
    Product(name="Funda Pasaporte Piel Sintética Diseño Moderno", description=lorem_ipsum.paragraph(), price=Decimal('9.99'), stock=140, tags="Viajes, Accesorios, Pasaporte, Funda"),
    Product(name="Etiquetas Identificadoras Maletas Aluminio (Pack 4)", description=lorem_ipsum.paragraph(), price=Decimal('11.50'), stock=280, tags="Viajes, Accesorios, Identificación, Maleta"),
    Product(name="Riñonera de Viaje Delgada Múltiples Bolsillos", description=lorem_ipsum.paragraph(), price=Decimal('17.80'), stock=95, tags="Viajes, Accesorios, Riñonera, Seguridad"),
    Product(name="Bolsa de Viaje Plegable Ligera Gran Capacidad", description=lorem_ipsum.paragraph(), price=Decimal('24.00'), stock=85, tags="Viajes, Equipaje, Bolsa Plegable, Ligera"),
    Product(name="Diario de Viaje Cuaderno Notas Piel Sintética", description=lorem_ipsum.paragraph(), price=Decimal('20.00'), stock=70, tags="Viajes, Accesorios, Diario, Recuerdos"),
    Product(name="Tapones Oídos Silicona Reducción Ruido Viaje (Estuche)", description=lorem_ipsum.paragraph(), price=Decimal('8.95'), stock=300, tags="Viajes, Confort, Tapones Oídos, Ruido"),
]